FROM ubuntu:16.04
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "python3", "python3-venv", "python3-dev", "build-essential"]
RUN ["apt-get", "install", "-y", "python3-pip"]
COPY deploy/build-env.sh /opt/build-env.sh
ENTRYPOINT ["sh", "/opt/build-env.sh"]
