FROM ubuntu:16.04
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "python3", "python3-venv", "python3-dev", "build-essential"]
COPY deploy/build-env.sh /opt/build-env.sh
ENTRYPOINT ["sh", "/opt/build-env.sh"]
CMD ["/home/DEV.T1.TBS-SCT.GC.CA/dsamojle-ps/"]
