version: 2
jobs:
  track_web:
    docker:
      - image: "circleci/python:3.5.5"
      - image: "mongo:3.6.2"
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
      - run:
          command: |
              ./utils/sync_dependencies.py setup.py requirements.txt
          name: "Check dependency lists are synced"
      - run:
          command: |
              python3 -m venv .env
              . .env/bin/activate
              pip install -r requirements.txt
              pip install -e .[development]
          name: "Installing dependencies"
      - save_cache:
          key: "deps1-{{ .Branch }}-{{ checksum \"requirements.txt\" }}"
          paths:
            - .env
      - run:
          command: |
              . .env/bin/activate
              # pylint src tests -- Major overhaul needed to not fail linting, not including linting in tests for now
              # mypy src tests
              pytest --cov=track tests
          name: "Running tests"
    working_directory: ~/repo
  deploy_site:
    docker:
      - image: docker:17.12.1-ce-git
    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker
      - run:
          command: |
              docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
              docker build  -t "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}" -t "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:latest" .
              docker push "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
              docker push "${DOCKER_REGISTRY}/${DOCKER_NAMESPACE}/${CIRCLE_PROJECT_REPONAME}:latest"
          name: "Build and Deploy Website Docker Image"
    working_directory: ~/repo
  build_package:
    docker:
      - image: ubuntu:xenial
    working_directory: /home/DEV.T1.TBS-SCT.GC.CA/dsamojle-ps
    steps:
      - checkout
      - run:
          command: |
              apt-get update
              apt-get install -y python3 python3-venv python3-dev build-essential
              python3 -m venv .venv
              . .venv/bin/activate
              pip install wheel
              pip install -r requirements.txt
              tar -czvf track-web.tar.gz .venv track
      - store_artifacts:
          path: /home/DEV.T1.TBS-SCT.GC.CA/dsamojle-ps/track-web.tar.gz
          
workflows:
  version: 2
  tracker:
    jobs:
      - track_web
      - build_package:
         requires:
            - track_web